### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by iannellog** [FrancescaR11/ESERCIZIO_FILESYSTEM#1]
Ho provato a eseguire e compaiono i seguenti warning

> /Users/iannello/Home/Didattica/Programmazione/esame/Gruppo2/ESERCIZIO_FILESYSTEM/FILESYSTEM_CON_CLASSI.py:219: DeprecationWarning: Call to deprecated function get_sheet_names (Use wb.sheetnames).
>   nomi_fogli=(excel_document.get_sheet_names()) # Salvo il nome dei fogli in una lista
> /Users/iannello/Home/Didattica/Programmazione/esame/Gruppo2/ESERCIZIO_FILESYSTEM/FILESYSTEM_CON_CLASSI.py:222: DeprecationWarning: Call to deprecated function get_sheet_by_name (Use wb[sheetname]).
>   sheet = excel_document.get_sheet_by_name(nome)

Vedete se riuscite a toglierli

**Comment by FrancescaR11** [comment]
Abbiamo eliminato i warning
